# Generated by Django 4.0.2 on 2022-02-27 11:30

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220226_2132'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signup',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
